### ISSUE TITLE
Is it possible to use this way for surface pro 7 plus? 11th Gen CPU

### ISSUE THREAD

**Issue by react-native-engineer** [balopez83/Surface-Pro-7-Hackintosh#11]

**Comment by balopez83** [comment]
@react-native-engineer no not at all.

The 11th gen cpu and graphics were never supported in any real Mac and so there would be no graphics support even if you were able to boot.

The only way to even have a chance in booting would be to spoof the CPU and force VESA graphics. Booting in VESA mode would be an unusable experience because of the high resolution of the screen which will make the screen freeze constantly and doing anything will take forever.

I'm sorry to provide the bad news.

**Comment by react-native-engineer** [comment]
@balopez83 Thank you for kind reply
