### ISSUE TITLE
secure boot error

### ISSUE THREAD

**Issue by Kabbutino** [balopez83/Surface-Pro-7-Hackintosh#12]
hi, after i install macOS on my surface i've got this error ![image](https://github.com/user-attachments/assets/2213f616-4a47-493e-83fe-92baa1b0a628) 

Veriftying shin SHAT data failed: Security Policy Violation
Sonething has gone seriously urong: SRAT self-check failed: Security Policy Violation

**Comment by Kabbutino** [comment]
yup, i installed ventura on my surface and so, do i format all my ssd and reinstall macOS?

**Comment by balopez83** [comment]
@Kabbutino A quick google search and it appears to be a Windows and/or Linux issue though is usually caused by Windows. You will need to clear the certificates and have windows register itself. 

If you don't have windows on your machine anymore then you likely have something that didn't get cleared and so clearing the certificates and then completely wiping the drive and reinstalling everything including the EFI will likely resolve it.

**Comment by Kabbutino** [comment]
or it's not better install macOS first and windows with bootcamp?

**Comment by balopez83** [comment]
@Kabbutino Yes I would always install Windows secondary to macOS and also ensure that macOS is the first partition after the EFI.

**Comment by Kabbutino** [comment]
nothing I've got the same error :(

**Comment by Kabbutino** [comment]
sorry but what's the name of that certificate because now i reinstalled windows and idk what certificate is

**Comment by balopez83** [comment]
@Kabbutino it occurs to me you might not have turned on 3rd party certificates in your UEFI. Make sure that is done first. 

You shouldn't need to register a certificate, only clear them. This can be done in the UEFI. 

You would need to follow one of the guides online for clearing and refreshing the security certificates if that doesn't work. This can apparently be done in both Windows and Linux. 

It's also possible that Microsoft did another upgrade to their firmware requiring you to just turn off secure boot in the UEFI until a workaround can be done to update security in OpenCore. I doubt this is the issue though since this security error doesn't seem to be widespread.

**Comment by Kabbutino** [comment]
@balopez83 yup i activated that option, but idk what is that certificate :(

**Comment by Kabbutino** [comment]
@balopez83 but if i disable the secure boot can i risk a brick?

**Comment by balopez83** [comment]
@Kabbutino The certificate is built in so nothing to look for. Windows & Ubuntu registers them which I don't have instructions for. OpenCore has to be built with them and it's very complicated to do which is why I don't provide instructions for that. 

There is no risk of bricking by turning off secure boot. You will only have an icon on the screen at boot that will let you know it's turned off.

**Comment by Kabbutino** [comment]
hey bro, in the end, in this days, I solved the problem of the secure boot with ubuntu and the terminal

**Comment by Gab6984** [comment]
> hey mec, au final, ces derniers jours, j'ai résolu le problème du démarrage sécurisé avec ubuntu et le terminal

Hello, did you have to install Ubuntu to solve the problem?

**Comment by balopez83** [comment]
@Gab6984 he had to use a Linux live usb. Basically Microsoft updated the boot loader and killed off some older keys. You have to register new keys using Linux or windows to enable secure boot.

**Comment by balopez83** [comment]
@Gab6984 I haven't attempted this but will let @Kabbutino respond on this if it was resolved. At some point I do plan on issuing a new release that should be able to resolve this though I have limited time and cannot focus on this right now. Since this is easily bypassed by turning off secure boot it has honestly been low priority for me. 

If you are unable to get the sbat method working I would simply turn off secure boot until I can update the secure boot keys to ones that the Surface/Microsoft will accept.
