### ISSUE TITLE
I can't boot when turn on secure boot 

### ISSUE THREAD

**Issue by kaseru** [balopez83/Surface-Pro-7-Hackintosh#4]
I am so grateful for your wonderful project.
I'm having an error with secure boot. I followed the instructions (using the latest EFI). But when booting and turning on secure boot . I received a warning as shown in the image.
 I have tried updating to the latest firmware. But luck still didn't happen.
I can only boot into macos after turning off secure boot.
Please suggest what I can do.
Thank you!
![IMG_6361](https://github.com/balopez83/Surface-Pro-7-Hackintosh/assets/5975972/ec974e55-5ca9-4086-9344-c5a9d2e1ab36)

**Comment by balopez83** [comment]
@kaseru How did you install the latest release? I ask because if the entire EFI was not replaced you can have this issue. In order for secure boot to work properly you would have to replace the entire EFI as provided in the latest release and should include the latest releases Boot, Grub, and OC folders within the EFI folder. 

You can also try booting with a clean EFI on USB installer and see if that works with secure boot on. If that works try the following:
Reset your Surface NVRAM as that is likely the issue. This can be done in the OpenCore menu (press spacebar if you don't see the option in OpenCore). 
If it still doesn't work, I would suggest completely wiping the entire drive, resetting NVRAM again and attempting to boot (which will give you the same error above). 
Then attempt to install using a USB with the latest clean EFI and install the latest EFI after installing macOS again.

**Comment by kaseru** [comment]
@balopez83 Thank you very much. I was successful.
I'm missing the Grub folder, because previously I only used files in your EFI.
I also need to delete all of windows' EFI area (which has a capacity of 100M). Before I deleted it, it still didn't seem to work. I really don't know if this is the cause.
I also need to reset NVRam.
And now it works fine with secure boot enabled.
Once again, thank you so much for your great work!

**Comment by balopez83** [comment]
@kaseru Glad to hear it is now working. So the Windows folder shouldn't break things and is required if you are trying to dual boot with Windows. Also having an EFI partition of only 100mb is really small and won't allow you to dual boot if thats something you are interested in. I assume you let macOS set the partitions which is why you only have 100mb. 

If you want to dual boot, I would recommend using an Ubuntu live USB disk and using Gparted to create a 500mb or even 1gb partition and be sure to set the flags to enable it to be used as the boot partition. If you choose a 1gb size partition it will allow you to also add a web recovery image to the partition so you could restore macOS over wifi without the need for a USB installer anymore. There are some guides for what is needed but generally you have an additional folder next to the EFI folder and you have a special file that is usually between 500-700 mb in size that will allow you to boot a web recovery similar to how a real mac would recover itself. You would then be able to launch the web recovery by hitting the space bar and then select the recovery you chose to add. 

If you don't want to do the above stuff but do want to dual boot, you should have an absolute minimum of a 200mb EFI partition. Windows automatically creates this partition from a clean (no partitioned) drive and you could work from that. If you have no desire to dual boot then you can leave it as is having removed your Windows folder in your EFI partition. 


Hope that helps a little. 

Since this is now working for you I am going to close this issue. Feel free to reach back out though if you have other questions on this.
