### ISSUE TITLE
Open core won't boot

### ISSUE THREAD

**Issue by albcal** [balopez83/Surface-Pro-7-Hackintosh#6]
I have a surface pro 7 i5 128gb ssd
I Installed succesfully macos sonoma with windows 10, but after drivers and firmware update on windows, open core won't boot, It stuck on windows logo

**Comment by balopez83** [comment]
@albcal This is common. Either it's because windows has updated your firmware to be incompatible at which point turning off secure boot will fix it or it has damaged the OpenCore EFI at which point you must copy the entire EFI back to the EFI partition making sure you copy your windows partition currently located on your EFI to the new OpenCore EFI you replace it with. If you fail to backup and copy over your windows partition then you will not be able to boot windows again.

**Comment by albcal** [comment]
I did it, my EFI Folder structure is
EFI---
      -BOOT
      -Microsoft
      -OC
But same result, I tried badstorn EFI and It loads.

**Comment by albcal** [comment]
Now It works, I copied the EFI without the SecureBootOn mods and now It works.

Thankyou!
